import type { PatientData } from "./ai-diagnostics"

// Sample patient data for demonstration purposes
export const samplePatientData: PatientData = {
  demographics: {
    age: 62,
    sex: "male",
    ethnicity: "Caucasian",
    weight: 92,
    height: 175,
    bmi: 30.1,
    smokingStatus: "former",
    alcoholUse: "moderate",
  },
  history: [
    {
      id: "cond-1",
      category: "condition",
      name: "Hypertension",
      status: "active",
      dateRecorded: "2018-05-12",
      details: "Diagnosed with essential hypertension, currently managed with medication",
    },
    {
      id: "cond-2",
      category: "condition",
      name: "Type 2 Diabetes Mellitus",
      status: "active",
      dateRecorded: "2019-03-22",
      details: "Diagnosed with type 2 diabetes, currently managed with oral medications",
    },
    {
      id: "cond-3",
      category: "condition",
      name: "Hyperlipidemia",
      status: "active",
      dateRecorded: "2018-05-12",
      details: "Elevated LDL cholesterol",
    },
    {
      id: "cond-4",
      category: "condition",
      name: "Chest Pain",
      status: "active",
      dateRecorded: "2023-04-15",
      details: "Intermittent chest pain, worse with exertion",
      severity: "moderate",
    },
    {
      id: "cond-5",
      category: "condition",
      name: "Fatigue",
      status: "active",
      dateRecorded: "2023-04-01",
      details: "Increasing fatigue over past 3 months",
      severity: "moderate",
    },
    {
      id: "med-1",
      category: "medication",
      name: "Metformin 1000mg",
      status: "active",
      dateRecorded: "2019-03-22",
      details: "1 tablet twice daily",
    },
    {
      id: "med-2",
      category: "medication",
      name: "Lisinopril 20mg",
      status: "active",
      dateRecorded: "2018-05-15",
      details: "1 tablet daily",
    },
    {
      id: "med-3",
      category: "medication",
      name: "Atorvastatin 40mg",
      status: "active",
      dateRecorded: "2018-05-15",
      details: "1 tablet daily at bedtime",
    },
    {
      id: "med-4",
      category: "medication",
      name: "Aspirin 81mg",
      status: "active",
      dateRecorded: "2020-01-10",
      details: "1 tablet daily",
    },
    {
      id: "proc-1",
      category: "procedure",
      name: "Coronary Angiogram",
      dateRecorded: "2020-01-05",
      details: "Showed 40% stenosis in LAD, non-obstructive CAD",
    },
    {
      id: "proc-2",
      category: "procedure",
      name: "Stress Echocardiogram",
      dateRecorded: "2022-11-12",
      details: "Normal wall motion, no ischemia detected",
    },
    {
      id: "fam-1",
      category: "familyHistory",
      name: "Coronary Artery Disease",
      dateRecorded: "2018-05-12",
      details: "Father had MI at age 58, mother had MI at age 65",
    },
    {
      id: "fam-2",
      category: "familyHistory",
      name: "Type 2 Diabetes",
      dateRecorded: "2018-05-12",
      details: "Mother and maternal grandmother had type 2 diabetes",
    },
    {
      id: "soc-1",
      category: "socialHistory",
      name: "Former Smoker",
      dateRecorded: "2018-05-12",
      details: "Smoked 1 pack per day for 25 years, quit 10 years ago",
    },
    {
      id: "life-1",
      category: "lifestyle",
      name: "Sedentary Lifestyle",
      status: "active",
      dateRecorded: "2022-02-15",
      details: "Minimal physical activity, desk job",
    },
  ],
}

// Sample test results for demonstration
export const sampleTestResults = [
  {
    id: "test-1",
    name: "Troponin",
    value: "0.04",
    unit: "ng/mL",
    referenceRange: "0.00-0.03",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-2",
    name: "BNP",
    value: "180",
    unit: "pg/mL",
    referenceRange: "0-100",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-3",
    name: "Glucose",
    value: "165",
    unit: "mg/dL",
    referenceRange: "70-99",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-4",
    name: "HbA1c",
    value: "7.2",
    unit: "%",
    referenceRange: "4.0-5.6",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-5",
    name: "Total Cholesterol",
    value: "210",
    unit: "mg/dL",
    referenceRange: "125-200",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-6",
    name: "LDL Cholesterol",
    value: "130",
    unit: "mg/dL",
    referenceRange: "0-100",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-7",
    name: "HDL Cholesterol",
    value: "38",
    unit: "mg/dL",
    referenceRange: "40-60",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-8",
    name: "Triglycerides",
    value: "210",
    unit: "mg/dL",
    referenceRange: "0-150",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-9",
    name: "Creatinine",
    value: "1.3",
    unit: "mg/dL",
    referenceRange: "0.7-1.2",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-10",
    name: "eGFR",
    value: "58",
    unit: "mL/min/1.73m²",
    referenceRange: "≥60",
    abnormal: true,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-11",
    name: "White Blood Cell Count",
    value: "9800",
    unit: "cells/µL",
    referenceRange: "4500-11000",
    abnormal: false,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-12",
    name: "Hemoglobin",
    value: "13.5",
    unit: "g/dL",
    referenceRange: "13.5-17.5",
    abnormal: false,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-13",
    name: "Platelets",
    value: "250000",
    unit: "cells/µL",
    referenceRange: "150000-450000",
    abnormal: false,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-14",
    name: "Sodium",
    value: "138",
    unit: "mmol/L",
    referenceRange: "135-145",
    abnormal: false,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
  {
    id: "test-15",
    name: "Potassium",
    value: "4.2",
    unit: "mmol/L",
    referenceRange: "3.5-5.0",
    abnormal: false,
    critical: false,
    date: "2023-04-16T08:30:00",
  },
]
